address: [127.0.0.1:6379]
username:
password: 1qaz2wsx12
# redis Mode, including "standalone","cluster","sentinel"
redisMode: "standalone"
db: 0
maxRetry: 10
poolSize: 100
# Sentinel configuration (only used when redisMode is "sentinel")
sentinelMode:
  masterName: "redis-master"
  sentinelsAddrs: ["127.0.0.1:6379"]
  routeByLatency: true
  routeRandomly: true
